// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Todo = require("./Todo.bs.js");
var React = require("react");
var ReactDom = require("react-dom");

var rootElement = document.querySelector("#myapp");

if (!(rootElement == null)) {
  ReactDom.render(React.createElement(Todo.Todo.make, {}), rootElement);
}

/* rootElement Not a pure module */
